export const CONFIG = [
  {
    id: 'providers',
    en: 'Providers (TCP 16-20)',
    sites: [
      { d: 'www.mobil.com.se', flag: '🇵🇱', name: 'Akamai' },
      { d: 'cdn.apple-mapkit.com', flag: '🇸🇪', name: 'Akamai' },
      { d: 'vibersporocila.akton.si', flag: '🇩🇪', name: 'AWS' },
      { d: 'corp.kaltura.com', flag: '🇺🇸', name: 'AWS' },
      { d: 'cdn.eso.org', flag: '🇺🇸', name: 'CDN77' },
      { d: 'hertzen.com', flag: '🇨🇦', name: 'Cloudflare' },
      { d: 'justice.gov', flag: '🇨🇦', name: 'Cloudflare' },
      { d: 'img.wzstats.gg', flag: '🇺🇸', name: 'Cloudflare' },
      { d: 'esm.sh', flag: '🇺🇸', name: 'Cloudflare' },
      { d: 'ctbnew.netmania.hu', flag: '🇫🇷', name: 'Contabo' },
      { d: 'oddremedies.com', flag: '🇫🇷', name: 'Contabo' },
      { d: 'ui-arts.com', flag: '🇩🇪', name: 'DigitalOcean' },
      { d: 'africa-s.org', flag: '🇬🇧', name: 'DigitalOcean' },
      { d: 'admin.survey54.com', flag: '🇬🇧', name: 'DigitalOcean' },
      { d: 'ssl.p.jwpcdn.com', flag: '🇨🇦', name: 'Fastly' },
      { d: 'www.jetblue.com', flag: '🇺🇸', name: 'Fastly' },
      { d: 'buyvm.net', flag: '🇺🇸', name: 'FT/BuyVM' },
      { d: 'dmvideo.download', flag: '🇺🇸', name: 'FT/BuyVM' },
      { d: 'gcore.com', flag: '🇱🇺', name: 'Gcore' },
      { d: 'api.usercentrics.eu', flag: '🇺🇸', name: 'Google Cloud' },
      { d: 'widgets.reputation.com', flag: '🇺🇸', name: 'Google Cloud' },
      { d: 'king.hr', flag: '🇩🇪', name: 'Hetzner' },
      { d: 'mail.server.apaone.com', flag: '🇩🇪', name: 'Hetzner' },
      { d: '251b5cd9.nip.io', flag: '🇫🇮', name: 'Hetzner' },
      { d: 'nioges.com', flag: '🇫🇮', name: 'Hetzner' },
      { d: '5fd8bdae.nip.io', flag: '🇫🇮', name: 'Hetzner' },
      { d: '5fd8bca5.nip.io', flag: '🇫🇮', name: 'Hetzner' },
      { d: 'elecane.com', flag: '🇺🇸', name: 'Melbicom' },
      { d: 'sh00065.hostgator.com', flag: '🇪🇸', name: 'Oracle' },
      { d: 'vps.inprodec.com', flag: '🇸🇬', name: 'Oracle' },
      { d: 'www.adwin.fr', flag: '🇫🇷', name: 'OVH' },
      { d: 'www.emca.be', flag: '🇫🇷', name: 'OVH' },
      { d: 'www.velivole.fr', flag: '🇳🇱', name: 'Scaleway' },
      { d: 'gertrud.tv', flag: '🇩🇪', name: 'Vultr' },
      { d: 'us.rudder.qntmnet.com', flag: '🇺🇸', name: 'Vultr' },
    ],
  },
  {
    id: 'social_intl',
    en: 'Social Media (International)',
    sites: [
      { d: 'twitter.com', flag: '🇺🇸', name: 'X / Twitter' },
      { d: 'facebook.com', flag: '🇺🇸', name: 'Facebook' },
      { d: 'instagram.com', flag: '🇺🇸', name: 'Instagram' },
      { d: 'tiktok.com', flag: '🇨🇳', name: 'TikTok' },
      { d: 'linkedin.com', flag: '🇺🇸', name: 'LinkedIn' },
      { d: 'reddit.com', flag: '🇺🇸', name: 'Reddit' },
      { d: 't.me', flag: '🇬🇧', name: 'Telegram', svc: 'Telegram' },
      { d: 'telegram.org', flag: '🇬🇧', name: 'Telegram Web', svc: 'Telegram' },
      { d: 'snapchat.com', flag: '🇺🇸', name: 'Snapchat' },
      { d: 'pinterest.com', flag: '🇺🇸', name: 'Pinterest' },
      { d: 'threads.net', flag: '🇺🇸', name: 'Threads' },
      { d: 'mastodon.social', flag: '🇩🇪', name: 'Mastodon' },
    ],
  },
  {
    id: 'social_ru',
    en: 'Social Media (Russian)',
    sites: [
      { d: 'vk.com', flag: '🇷🇺', name: 'ВКонтакте' },
      { d: 'ok.ru', flag: '🇷🇺', name: 'Одноклассники' },
      { d: 'dzen.ru', flag: '🇷🇺', name: 'Дзен' },
      { d: 'pikabu.ru', flag: '🇷🇺', name: 'Pikabu' },
      { d: 'livejournal.com', flag: '🇷🇺', name: 'LiveJournal' },
      { d: 'rutube.ru', flag: '🇷🇺', name: 'RuTube' },
    ],
  },
  {
    id: 'dating',
    en: 'Dating',
    sites: [
      { d: 'tinder.com', flag: '🇺🇸', name: 'Tinder' },
      { d: 'bumble.com', flag: '🇺🇸', name: 'Bumble' },
      { d: 'grindr.com', flag: '🇺🇸', name: 'Grindr' },
      { d: 'pure.app', flag: '🇺🇸', name: 'Pure' },
      { d: 'badoo.com', flag: '🇷🇺', name: 'Badoo' },
      { d: 'mamba.ru', flag: '🇷🇺', name: 'Mamba' },
      { d: 'loveplanet.ru', flag: '🇷🇺', name: 'LovePlanet' },
      { d: 'okcupid.com', flag: '🇺🇸', name: 'OkCupid' },
      { d: 'twinby.com', flag: '🇷🇺', name: 'Twinby' },
      { d: 'vk.com/vkdating', flag: '🇷🇺', name: 'VK Знакомства' },
    ],
  },
  {
    id: 'video',
    en: 'Video Streaming',
    sites: [
      { d: 'youtube.com', flag: '🇺🇸', name: 'YouTube' },
      { d: 'netflix.com', flag: '🇺🇸', name: 'Netflix' },
      { d: 'max.com', flag: '🇺🇸', name: 'Max (HBO)' },
      { d: 'disneyplus.com', flag: '🇺🇸', name: 'Disney+' },
      { d: 'primevideo.com', flag: '🇺🇸', name: 'Prime Video' },
      { d: 'twitch.tv', flag: '🇺🇸', name: 'Twitch' },
      { d: 'vimeo.com', flag: '🇺🇸', name: 'Vimeo' },
      { d: 'dailymotion.com', flag: '🇫🇷', name: 'Dailymotion' },
      { d: 'vkvideo.ru', flag: '🇷🇺', name: 'VK Видео' },
      { d: 'ivi.ru', flag: '🇷🇺', name: 'ivi' },
      { d: 'okko.tv', flag: '🇷🇺', name: 'Okko' },
      { d: 'kinopoisk.ru', flag: '🇷🇺', name: 'Кинопоиск' },
    ],
  },
  {
    id: 'news_intl',
    en: 'News (International)',
    sites: [
      { d: 'nytimes.com', flag: '🇺🇸', name: 'NY Times' },
      { d: 'cnn.com', flag: '🇺🇸', name: 'CNN' },
      { d: 'cbsnews.com', flag: '🇺🇸', name: 'CBS News' },
      { d: 'bbc.com', flag: '🇬🇧', name: 'BBC' },
      { d: 'theguardian.com', flag: '🇬🇧', name: 'The Guardian' },
      { d: 'reuters.com', flag: '🇬🇧', name: 'Reuters' },
      { d: 'dw.com', flag: '🇩🇪', name: 'Deutsche Welle' },
      { d: 'france24.com', flag: '🇫🇷', name: 'France 24' },
      { d: 'lemonde.fr', flag: '🇫🇷', name: 'Le Monde' },
      { d: 'abc.net.au', flag: '🇦🇺', name: 'ABC Australia' },
      { d: 'sbs.com.au', flag: '🇦🇺', name: 'SBS Australia' },
      { d: 'timesofindia.indiatimes.com', flag: '🇮🇳', name: 'Times of India' },
      { d: 'ndtv.com', flag: '🇮🇳', name: 'NDTV' },
      { d: 'scmp.com', flag: '🇭🇰', name: 'SCMP' },
      { d: 'www.nhk.or.jp', flag: '🇯🇵', name: 'NHK' },
      { d: 'aljazeera.com', flag: '🇶🇦', name: 'Al Jazeera' },
    ],
  },
  {
    id: 'news_ru_gov',
    en: 'News (Russian / State)',
    sites: [
      { d: 'rt.com', flag: '🇷🇺', name: 'RT' },
      { d: 'tass.ru', flag: '🇷🇺', name: 'ТАСС' },
      { d: 'ria.ru', flag: '🇷🇺', name: 'РИА Новости' },
      { d: 'interfax.ru', flag: '🇷🇺', name: 'Интерфакс' },
      { d: 'kommersant.ru', flag: '🇷🇺', name: 'Коммерсантъ' },
      { d: 'lenta.ru', flag: '🇷🇺', name: 'Лента.ру' },
      { d: 'rbc.ru', flag: '🇷🇺', name: 'РБК' },
    ],
  },
  {
    id: 'news_ru_opp',
    en: 'News (Russian / Opposition)',
    sites: [
      { d: 'meduza.io', flag: '🇱🇻', name: 'Медуза' },
      { d: 'novayagazeta.eu', flag: '🇱🇻', name: 'Новая газета' },
      { d: 'currenttime.tv', flag: '🇺🇸', name: 'Настоящее время' },
      { d: 'theins.ru', flag: '🇱🇻', name: 'The Insider' },
      { d: 'holod.media', flag: '🇱🇻', name: 'Холод' },
      { d: 'verstka.media', flag: '🇱🇻', name: 'Вёрстка' },
      { d: 'mediazona.ca', flag: '🇨🇦', name: 'Медиазона' },
      { d: 'ovd.news', flag: '🇱🇻', name: 'ОВД-Инфо' },
    ],
  },
  {
    id: 'search',
    en: 'Search Engines',
    sites: [
      { d: 'google.com', flag: '🇺🇸', name: 'Google' },
      { d: 'yandex.ru', flag: '🇷🇺', name: 'Яндекс' },
      { d: 'bing.com', flag: '🇺🇸', name: 'Bing' },
      { d: 'duckduckgo.com', flag: '🇺🇸', name: 'DuckDuckGo' },
      { d: 'yahoo.com', flag: '🇺🇸', name: 'Yahoo' },
      { d: 'baidu.com', flag: '🇨🇳', name: 'Baidu' },
      { d: 'ecosia.org', flag: '🇩🇪', name: 'Ecosia' },
    ],
  },
  {
    id: 'torrents',
    en: 'Torrents',
    sites: [
      { d: 'thepiratebay.org', flag: '', name: 'The Pirate Bay' },
      { d: 'rutracker.org', flag: '🇷🇺', name: 'RuTracker' },
      { d: '1337x.to', flag: '', name: '1337x' },
      { d: 'rutor.info', flag: '🇷🇺', name: 'Rutor' },
      { d: 'nnmclub.to', flag: '🇷🇺', name: 'NNM-Club' },
      { d: 'flibusta.is', flag: '🇷🇺', name: 'Flibusta' },
      { d: 'nyaa.si', flag: '🇯🇵', name: 'Nyaa' },
      { d: 'rarbg.to', flag: '', name: 'RARBG' },
      { d: 'kinozal.tv', flag: '🇷🇺', name: 'Кинозал' },
    ],
  },
  {
    id: 'messengers',
    en: 'Messengers (service endpoints)',
    sites: [
      { d: 'chat.signal.org', flag: '🇺🇸', name: 'Signal API', svc: 'Signal' },
      { d: 'storage.signal.org', flag: '🇺🇸', name: 'Signal Storage', svc: 'Signal' },
      { d: 'cdn.signal.org', flag: '🇺🇸', name: 'Signal CDN', svc: 'Signal' },
      { d: 'web.whatsapp.com', flag: '🇺🇸', name: 'WhatsApp Web', svc: 'WhatsApp' },
      { d: 'pps.whatsapp.net', flag: '🇺🇸', name: 'WhatsApp Media', svc: 'WhatsApp' },
      { d: 'core.telegram.org', flag: '🇬🇧', name: 'Telegram API', svc: 'Telegram' },
      { d: 'web.telegram.org', flag: '🇬🇧', name: 'Telegram Web', svc: 'Telegram' },
      { d: 'viber.com', flag: '🇯🇵', name: 'Viber', svc: 'Viber' },
      { d: 'dl.viber.com', flag: '🇯🇵', name: 'Viber CDN', svc: 'Viber' },
      { d: 'web.wechat.com', flag: '🇨🇳', name: 'WeChat Web', svc: 'WeChat' },
      { d: 'wx.qq.com', flag: '🇨🇳', name: 'WeChat API', svc: 'WeChat' },
      { d: 'talk.kakao.com', flag: '🇰🇷', name: 'KakaoTalk', svc: 'KakaoTalk' },
      { d: 'bip.com', flag: '🇹🇷', name: 'BiP', svc: 'BiP' },
      { d: 'line.me', flag: '🇯🇵', name: 'LINE', svc: 'LINE' },
      { d: 'discord.com', flag: '🇺🇸', name: 'Discord', svc: 'Discord' },
      { d: 'gateway.discord.gg', flag: '🇺🇸', name: 'Discord Gateway', svc: 'Discord' },
    ],
  },
  {
    id: 'privacy',
    en: 'Privacy / VPN',
    sites: [
      { d: 'torproject.org', flag: '', name: 'Tor Project' },
      { d: 'proton.me', flag: '🇨🇭', name: 'Proton' },
      { d: 'mullvad.net', flag: '🇸🇪', name: 'Mullvad' },
      { d: 'nordvpn.com', flag: '🇱🇹', name: 'NordVPN' },
      { d: 'wireguard.com', flag: '', name: 'WireGuard' },
    ],
  },
  {
    id: 'hosting',
    en: 'Hosting / Registrars',
    sites: [
      { d: 'aws.amazon.com', flag: '🇺🇸', name: 'AWS' },
      { d: 'cloud.google.com', flag: '🇺🇸', name: 'Google Cloud' },
      { d: 'azure.microsoft.com', flag: '🇺🇸', name: 'Azure' },
      { d: 'vultr.com', flag: '🇺🇸', name: 'Vultr' },
      { d: 'hetzner.com', flag: '🇩🇪', name: 'Hetzner' },
      { d: 'ovh.com', flag: '🇫🇷', name: 'OVH' },
      { d: 'digitalocean.com', flag: '🇺🇸', name: 'DigitalOcean' },
      { d: 'linode.com', flag: '🇺🇸', name: 'Linode' },
      { d: 'namecheap.com', flag: '🇺🇸', name: 'Namecheap' },
      { d: 'cloudflare.com', flag: '🇺🇸', name: 'Cloudflare' },
      { d: 'godaddy.com', flag: '🇺🇸', name: 'GoDaddy' },
      { d: 'reg.ru', flag: '🇷🇺', name: 'REG.RU' },
      { d: 'selectel.ru', flag: '🇷🇺', name: 'Selectel' },
      { d: 'timeweb.com', flag: '🇷🇺', name: 'Timeweb' },
    ],
  },
  {
    id: 'tech',
    en: 'Tech / Forums',
    sites: [
      { d: 'ntc.party', flag: '🇩🇪', name: 'ntc.party' },
      { d: 'openwrt.org', flag: '🇩🇪', name: 'OpenWrt' },
      { d: 'news.ycombinator.com', flag: '🇺🇸', name: 'Hacker News' },
      { d: 'habr.com', flag: '🇷🇺', name: 'Хабр' },
      { d: 'stackoverflow.com', flag: '🇺🇸', name: 'Stack Overflow' },
      { d: 'github.com', flag: '🇺🇸', name: 'GitHub' },
      { d: 'gitlab.com', flag: '🇺🇸', name: 'GitLab' },
      { d: 'dev.to', flag: '🇺🇸', name: 'DEV' },
      { d: 'medium.com', flag: '🇺🇸', name: 'Medium' },
      { d: 'arxiv.org', flag: '🇺🇸', name: 'arXiv' },
      { d: 'opennet.ru', flag: '🇷🇺', name: 'OpenNET' },
      { d: '3dnews.ru', flag: '🇷🇺', name: '3DNews' },
    ],
  },
  {
    id: 'news_by',
    en: 'Media (Belarus)',
    sites: [
      { d: 'onliner.by', flag: '🇧🇾', name: 'Onliner' },
      { d: 'zerkalo.io', flag: '🇧🇾', name: 'Зеркало' },
      { d: 'spring96.org', flag: '🇧🇾', name: 'Вясна' },
      { d: 'belta.by', flag: '🇧🇾', name: 'БелТА' },
      { d: 'sb.by', flag: '🇧🇾', name: 'СБ Беларусь' },
      { d: 'naviny.by', flag: '🇧🇾', name: 'Naviny' },
      { d: 'belsat.eu', flag: '🇧🇾', name: 'Белсат' },
      { d: 'nashaniva.by', flag: '🇧🇾', name: 'Наша Ніва' },
      { d: 'kp.by', flag: '🇧🇾', name: 'КП Беларусь' },
      { d: 'reform.news', flag: '🇧🇾', name: 'Reform.news' },
    ],
  },
  {
    id: 'software',
    en: 'Software / Dev Tools',
    sites: [
      { d: 'archive.ubuntu.com', flag: '🇬🇧', name: 'Ubuntu' },
      { d: 'dl.fedoraproject.org', flag: '🇺🇸', name: 'Fedora' },
      { d: 'deb.debian.org', flag: '🇺🇸', name: 'Debian' },
      { d: 'archlinux.org', flag: '🇺🇸', name: 'Arch Linux' },
      { d: 'download.opensuse.org', flag: '🇩🇪', name: 'openSUSE' },
      { d: 'catalog.update.microsoft.com', flag: '🇺🇸', name: 'MS Update Catalog' },
      { d: 'download.microsoft.com', flag: '🇺🇸', name: 'MS Downloads' },
      { d: 'huggingface.co', flag: '🇺🇸', name: 'HuggingFace' },
      { d: 'kaggle.com', flag: '🇺🇸', name: 'Kaggle' },
      { d: 'pypi.org', flag: '🇺🇸', name: 'PyPI' },
      { d: 'npmjs.com', flag: '🇺🇸', name: 'npm' },
      { d: 'hub.docker.com', flag: '🇺🇸', name: 'Docker Hub' },
      { d: 'repo.anaconda.com', flag: '🇺🇸', name: 'Anaconda' },
      { d: 'crates.io', flag: '🇺🇸', name: 'crates.io' },
      { d: 'registry.terraform.io', flag: '🇺🇸', name: 'Terraform' },
    ],
  },
  {
    id: 'banks',
    en: 'Banks',
    sites: [
      { d: 'www.tbank.ru', flag: '🇷🇺', name: 'Т-Банк' },
      { d: 'sberbank.ru', flag: '🇷🇺', name: 'Сбербанк' },
      { d: 'alfabank.ru', flag: '🇷🇺', name: 'Альфа-Банк' },
      { d: 'raiffeisen.ru', flag: '🇷🇺', name: 'Райффайзен' },
      { d: 'chase.com', flag: '🇺🇸', name: 'Chase' },
      { d: 'bankofamerica.com', flag: '🇺🇸', name: 'Bank of America' },
      { d: 'wellsfargo.com', flag: '🇺🇸', name: 'Wells Fargo' },
      { d: 'www.hsbc.com', flag: '🇬🇧', name: 'HSBC' },
      { d: 'barclays.co.uk', flag: '🇬🇧', name: 'Barclays' },
      { d: 'lloydsbank.com', flag: '🇬🇧', name: 'Lloyds' },
      { d: 'natwest.com', flag: '🇬🇧', name: 'NatWest' },
      { d: 'intesasanpaolo.com', flag: '🇮🇹', name: 'Intesa Sanpaolo' },
      { d: 'unicredit.it', flag: '🇮🇹', name: 'UniCredit' },
      { d: 'www.unicreditbank.ru', flag: '🇷🇺', name: 'UniCredit Russia' },
      { d: 'santander.com', flag: '🇪🇸', name: 'Santander' },
      { d: 'bbva.com', flag: '🇪🇸', name: 'BBVA' },
      { d: 'bk.mufg.jp', flag: '🇯🇵', name: 'MUFG' },
      { d: 'www.mizuhobank.co.jp', flag: '🇯🇵', name: 'Mizuho' },
      { d: 'www.smbc.co.jp', flag: '🇯🇵', name: 'SMBC' },
    ],
  },
];
