export const CONFIG = [
  {
    id: 'providers',
    en: 'Providers (TCP 16-20)',
    ru: 'Провайдеры (TCP 16-20)',
    sites: [
      { d: 'www.mobil.com.se', flag: 'PL', name: 'Akamai' },
      { d: 'cdn.apple-mapkit.com', flag: 'SE', name: 'Akamai' },
      { d: 'vibersporocila.akton.si', flag: 'DE', name: 'AWS' },
      { d: 'corp.kaltura.com', flag: 'US', name: 'AWS' },
      { d: 'cdn.eso.org', flag: 'US', name: 'CDN77' },
      { d: 'hertzen.com', flag: 'CA', name: 'Cloudflare' },
      { d: 'justice.gov', flag: 'CA', name: 'Cloudflare' },
      { d: 'img.wzstats.gg', flag: 'US', name: 'Cloudflare' },
      { d: 'esm.sh', flag: 'US', name: 'Cloudflare' },
      { d: 'ctbnew.netmania.hu', flag: 'FR', name: 'Contabo' },
      { d: 'oddremedies.com', flag: 'FR', name: 'Contabo' },
      { d: 'ui-arts.com', flag: 'DE', name: 'DigitalOcean' },
      { d: 'africa-s.org', flag: 'GB', name: 'DigitalOcean' },
      { d: 'admin.survey54.com', flag: 'GB', name: 'DigitalOcean' },
      { d: 'ssl.p.jwpcdn.com', flag: 'CA', name: 'Fastly' },
      { d: 'www.jetblue.com', flag: 'US', name: 'Fastly' },
      { d: 'buyvm.net', flag: 'US', name: 'FT/BuyVM' },
      { d: 'dmvideo.download', flag: 'US', name: 'FT/BuyVM' },
      { d: 'gcore.com', flag: 'LU', name: 'Gcore' },
      { d: 'api.usercentrics.eu', flag: 'US', name: 'Google Cloud' },
      { d: 'widgets.reputation.com', flag: 'US', name: 'Google Cloud' },
      { d: 'king.hr', flag: 'DE', name: 'Hetzner' },
      { d: 'mail.server.apaone.com', flag: 'DE', name: 'Hetzner' },
      { d: 'nioges.com', flag: 'FI', name: 'Hetzner' },
      { d: '5fd8bdae.nip.io', flag: 'FI', name: 'Hetzner' },
      { d: '5fd8bca5.nip.io', flag: 'FI', name: 'Hetzner' },
      { d: 'elecane.com', flag: 'US', name: 'Melbicom' },
      { d: 'store.takeda.com', flag: 'NL', name: 'Microsoft/Azure' },
      { d: 'sh00065.hostgator.com', flag: 'ES', name: 'Oracle' },
      { d: 'vps.inprodec.com', flag: 'SG', name: 'Oracle' },
      { d: 'www.adwin.fr', flag: 'FR', name: 'OVH' },
      { d: 'www.emca.be', flag: 'FR', name: 'OVH' },
      { d: 'www.velivole.fr', flag: 'NL', name: 'Scaleway' },
      { d: 'gertrud.tv', flag: 'DE', name: 'Vultr' },
      { d: 'us.rudder.qntmnet.com', flag: 'US', name: 'Vultr' },
    ],
  },
  {
    id: 'geoblock',
    en: 'GeoBlock',
    ru: 'Гео-блок',
    checker: 'cdn-trace',
    sites: [
      {
        d: 'chatgpt.com',
        flag: 'US',
        name: 'ChatGPT',
        logo: '/openai.svg',
        blockedIn: ['CN', 'RU', 'BY', 'KP', 'CU', 'IR', 'SY', 'VE', 'MM'],
      },
      {
        d: 'claude.ai',
        flag: 'US',
        name: 'Claude',
        logo: '/anthropic.svg',
        blockedIn: ['CN', 'RU', 'BY', 'KP', 'CU', 'IR', 'SY'],
      },
      {
        d: 'grok.com',
        flag: 'US',
        name: 'Grok',
        logo: '/grokai.svg',
        blockedIn: ['CN', 'RU', 'KP', 'CU', 'IR', 'SY'],
      },
      {
        d: 'perplexity.ai',
        flag: 'US',
        name: 'Perplexity',
        logo: '/perplexityai.svg',
        blockedIn: ['CN', 'KP', 'CU', 'IR', 'SY'],
      },
      {
        d: 'notion.so',
        flag: 'US',
        name: 'Notion',
        logo: '/notion.svg',
        blockedIn: ['CN', 'RU', 'BY', 'KP', 'CU', 'IR', 'SY', 'VE', 'MM'],
      },
      {
        d: '4pda.to',
        flag: 'US',
        name: '4PDA',
        logo: '/4pda.png',
        blockedIn: ['RU'],
      },
      {
        d: 'swagger.io',
        flag: 'US',
        name: 'Swagger',
        logo: '/swagger.png',
        blockedIn: ['RU'],
      },
      {
        d: 'redis.io',
        flag: 'US',
        name: 'Redis',
        logo: '/redis.png',
        blockedIn: ['RU'],
      },
      {
        d: 'hostinger.com',
        flag: 'US',
        name: 'Hostinger',
        logo: '/hostinger.png',
        blockedIn: ['RU'],
      },
    ],
  },
  {
    id: 'social_intl',
    en: 'Social Media (International)',
    ru: 'Соцсети (международные)',
    sites: [
      { d: 'twitter.com', flag: 'US', name: 'X / Twitter', logo: '/twitter.svg' },
      { d: 'facebook.com', flag: 'US', name: 'Facebook', logo: '/facebook.webp' },
      { d: 'instagram.com', flag: 'US', name: 'Instagram', logo: '/instagram.png' },
      { d: 'tiktok.com', flag: 'CN', name: 'TikTok', logo: '/tiktok.svg' },
      { d: 'linkedin.com', flag: 'US', name: 'LinkedIn', logo: '/LinkedIn.png' },
      { d: 'reddit.com', flag: 'US', name: 'Reddit', logo: '/reddit.svg' },
      { d: 't.me', flag: 'GB', name: 'Telegram', svc: 'Telegram', logo: '/telegram.svg' },
      {
        d: 'telegram.org',
        flag: 'GB',
        name: 'Telegram Web',
        svc: 'Telegram',
        logo: '/telegram.svg',
      },
      { d: 'snapchat.com', flag: 'US', name: 'Snapchat', logo: '/snapchat.webp' },
      { d: 'pinterest.com', flag: 'US', name: 'Pinterest', logo: '/pinterest.svg' },
      { d: 'threads.net', flag: 'US', name: 'Threads', logo: '/threads.png' },
      { d: 'mastodon.social', flag: 'DE', name: 'Mastodon', logo: '/mastodon.jpg' },
    ],
  },
  {
    id: 'social_ru',
    en: 'Social Media (Russian)',
    ru: 'Соцсети (российские)',
    sites: [
      { d: 'vk.com', flag: 'RU', name: 'ВКонтакте', logo: '/vk.svg' },
      { d: 'ok.ru', flag: 'RU', name: 'Одноклассники', logo: '/ok.svg' },
      { d: 'dzen.ru', flag: 'RU', name: 'Дзен', logo: '/dzen.webp' },
      { d: 'pikabu.ru', flag: 'RU', name: 'Pikabu', logo: '/pikabu.svg' },
      { d: 'livejournal.com', flag: 'RU', name: 'LiveJournal', logo: '/livejournal.svg' },
      { d: 'rutube.ru', flag: 'RU', name: 'RuTube', logo: '/rutube.webp' },
    ],
  },
  {
    id: 'dating',
    en: 'Dating',
    ru: 'Знакомства',
    sites: [
      { d: 'tinder.com', flag: 'US', name: 'Tinder', logo: '/tinder.png' },
      { d: 'bumble.com', flag: 'US', name: 'Bumble', logo: '/bumble.png' },
      { d: 'grindr.com', flag: 'US', name: 'Grindr', logo: '/grindr.png' },
      { d: 'pure.app', flag: 'US', name: 'Pure', logo: '/pure.webp' },
      { d: 'badoo.com', flag: 'RU', name: 'Badoo', logo: '/badoo.png' },
      { d: 'mamba.ru', flag: 'RU', name: 'Mamba', logo: '/mamba.webp' },
      { d: 'loveplanet.ru', flag: 'RU', name: 'LovePlanet', logo: '/loveplanet.svg' },
      { d: 'okcupid.com', flag: 'US', name: 'OkCupid', logo: '/OkCupid.png' },
      { d: 'twinby.com', flag: 'RU', name: 'Twinby', logo: '/twinby.svg' },
      { d: 'vk.com/vkdating', flag: 'RU', name: 'VK Знакомства', logo: '/vkdating.svg' },
    ],
  },
  {
    id: 'video',
    en: 'Video Streaming',
    ru: 'Видеостриминг',
    sites: [
      { d: 'youtube.com', flag: 'US', name: 'YouTube', logo: '/youtube.webp' },
      { d: 'netflix.com', flag: 'US', name: 'Netflix', logo: '/netflix.png' },
      { d: 'max.com', flag: 'US', name: 'Max (HBO)', logo: '/maxhbo.png' },
      { d: 'disneyplus.com', flag: 'US', name: 'Disney+', logo: '/disneyplus.png' },
      { d: 'primevideo.com', flag: 'US', name: 'Prime Video', logo: '/primevideo.png' },
      { d: 'twitch.tv', flag: 'US', name: 'Twitch', logo: '/twitch.webp' },
      { d: 'vimeo.com', flag: 'US', name: 'Vimeo', logo: '/vimeo.png' },
      { d: 'dailymotion.com', flag: 'FR', name: 'Dailymotion', logo: '/dailymotion.png' },
      { d: 'vkvideo.ru', flag: 'RU', name: 'VK Видео', logo: '/vkvideo.webp' },
      { d: 'ivi.ru', flag: 'RU', name: 'ivi', logo: '/iviru.svg' },
      { d: 'okko.tv', flag: 'RU', name: 'Okko', logo: '/okko.jpg' },
      { d: 'kinopoisk.ru', flag: 'RU', name: 'Кинопоиск', logo: '/kinopoisk.svg' },
    ],
  },
  {
    id: 'news_intl',
    en: 'News (International)',
    ru: 'Новости (международные)',
    sites: [
      { d: 'nytimes.com', flag: 'US', name: 'NY Times', logo: '/NY-Times.png' },
      { d: 'cnn.com', flag: 'US', name: 'CNN', logo: '/CNN.png' },
      { d: 'cbsnews.com', flag: 'US', name: 'CBS News', logo: '/CBS-News.png' },
      { d: 'bbc.com', flag: 'GB', name: 'BBC', logo: '/bbc.png' },
      { d: 'theguardian.com', flag: 'GB', name: 'The Guardian', logo: '/The-Guardian.png' },
      { d: 'reuters.com', flag: 'GB', name: 'Reuters', logo: '/reuters.png' },
      { d: 'dw.com', flag: 'DE', name: 'Deutsche Welle', logo: '/Deutsche-Welle.png' },
      { d: 'france24.com', flag: 'FR', name: 'France 24', logo: '/France-24.png' },
      { d: 'lemonde.fr', flag: 'FR', name: 'Le Monde', logo: '/Le-Monde.png' },
      { d: 'abc.net.au', flag: 'AU', name: 'ABC Australia', logo: '/ABC-Australia.png' },
      { d: 'sbs.com.au', flag: 'AU', name: 'SBS Australia', logo: '/SBS-Australia.png' },
      {
        d: 'timesofindia.indiatimes.com',
        flag: 'IN',
        name: 'Times of India',
        logo: '/Times-of-India.png',
      },
      { d: 'ndtv.com', flag: 'IN', name: 'NDTV', logo: '/NDTV.png' },
      { d: 'scmp.com', flag: 'HK', name: 'SCMP', logo: '/SCMP.png' },
      { d: 'www.nhk.or.jp', flag: 'JP', name: 'NHK', logo: '/NHK.png' },
      { d: 'aljazeera.com', flag: 'QA', name: 'Al Jazeera', logo: '/Al Jazeera.png' },
    ],
  },
  {
    id: 'news_ru_gov',
    en: 'News (Russian / State)',
    ru: 'Новости (российские / госСМИ)',
    sites: [
      { d: 'rt.com', flag: 'RU', name: 'RT', logo: '/rt.com.webp' },
      { d: 'tass.ru', flag: 'RU', name: 'ТАСС', logo: '/tass.webp' },
      { d: 'ria.ru', flag: 'RU', name: 'РИА Новости', logo: '/ria.svg' },
      { d: 'interfax.ru', flag: 'RU', name: 'Интерфакс', logo: '/interfax.webp' },
      { d: 'kommersant.ru', flag: 'RU', name: 'Коммерсантъ', logo: '/kommersant.svg' },
      { d: 'lenta.ru', flag: 'RU', name: 'Лента.ру', logo: '/lentaru.png' },
      { d: 'rbc.ru', flag: 'RU', name: 'РБК', logo: '/rbc.svg' },
    ],
  },
  {
    id: 'news_ru_opp',
    en: 'News (Russian / Opposition)',
    ru: 'Новости (российские / оппозиция)',
    sites: [
      { d: 'meduza.io', flag: 'LV', name: 'Медуза', logo: '/meduza.png' },
      { d: 'novayagazeta.eu', flag: 'LV', name: 'Новая газета', logo: '/novayagazeta.png' },
      { d: 'currenttime.tv', flag: 'US', name: 'Настоящее время', logo: '/currenttime.png' },
      { d: 'theins.ru', flag: 'LV', name: 'The Insider', logo: '/The-Insider.png' },
      { d: 'holod.media', flag: 'LV', name: 'Холод', logo: '/holod.png' },
      { d: 'verstka.media', flag: 'LV', name: 'Вёрстка', logo: '/verstka.png' },
      { d: 'mediazona.ca', flag: 'CA', name: 'Медиазона', logo: '/mediazona.png' },
      { d: 'ovd.news', flag: 'LV', name: 'ОВД-Инфо', logo: '/ovd.png' },
    ],
  },
  {
    id: 'search',
    en: 'Search Engines',
    ru: 'Поисковики',
    sites: [
      { d: 'google.com', flag: 'US', name: 'Google', logo: '/google.svg' },
      { d: 'yandex.ru', flag: 'RU', name: 'Яндекс', logo: '/yandex.svg' },
      { d: 'bing.com', flag: 'US', name: 'Bing', logo: '/bing.svg' },
      { d: 'duckduckgo.com', flag: 'US', name: 'DuckDuckGo', logo: '/DuckDuckGo.png' },
      { d: 'yahoo.com', flag: 'US', name: 'Yahoo', logo: '/Yahoo.png' },
      { d: 'baidu.com', flag: 'CN', name: 'Baidu', logo: '/Baidu.png' },
      { d: 'ecosia.org', flag: 'DE', name: 'Ecosia', logo: '/Ecosia.png' },
    ],
  },
  {
    id: 'torrents',
    en: 'Torrents',
    ru: 'Торренты',
    sites: [
      { d: 'thepiratebay.org', flag: '', name: 'The Pirate Bay', logo: '/The_Pirate_Bay.png' },
      { d: 'rutracker.org', flag: 'RU', name: 'RuTracker', logo: '/rutracker.png' },
      { d: '1337x.to', flag: '', name: '1337x', logo: '/1337x.png' },
      { d: 'rutor.info', flag: 'RU', name: 'Rutor', logo: '/rutor.png' },
      { d: 'nnmclub.to', flag: 'RU', name: 'NNM-Club', logo: '/NNM-Club.png' },
      { d: 'flibusta.is', flag: 'RU', name: 'Flibusta', logo: '/Flibusta.jpg' },
      { d: 'nyaa.si', flag: 'JP', name: 'Nyaa' },
      { d: 'kinozal.tv', flag: 'RU', name: 'Кинозал' },
    ],
  },
  {
    id: 'messengers',
    en: 'Messengers (service endpoints)',
    ru: 'Мессенджеры (сервисные эндпоинты)',
    sites: [
      {
        d: 'chat.signal.org',
        flag: 'US',
        name: 'Signal API',
        svc: 'Signal',
        logo: '/signalmsg.webp',
      },
      {
        d: 'storage.signal.org',
        flag: 'US',
        name: 'Signal Storage',
        svc: 'Signal',
        logo: '/signalmsg.webp',
      },
      {
        d: 'cdn.signal.org',
        flag: 'US',
        name: 'Signal CDN',
        svc: 'Signal',
        logo: '/signalmsg.webp',
      },
      {
        d: 'web.whatsapp.com',
        flag: 'US',
        name: 'WhatsApp Web',
        svc: 'WhatsApp',
        logo: '/whatsapp.svg',
      },
      {
        d: 'pps.whatsapp.net',
        flag: 'US',
        name: 'WhatsApp Media',
        svc: 'WhatsApp',
        logo: '/whatsapp.svg',
      },
      {
        d: 'core.telegram.org',
        flag: 'GB',
        name: 'Telegram API',
        svc: 'Telegram',
        logo: '/telegram.svg',
      },
      {
        d: 'web.telegram.org',
        flag: 'GB',
        name: 'Telegram Web',
        svc: 'Telegram',
        logo: '/telegram.svg',
      },
      { d: 'viber.com', flag: 'JP', name: 'Viber', svc: 'Viber', logo: '/viber.webp' },
      { d: 'dl.viber.com', flag: 'JP', name: 'Viber CDN', svc: 'Viber', logo: '/viber.webp' },
      { d: 'web.wechat.com', flag: 'CN', name: 'WeChat Web', svc: 'WeChat', logo: '/wechat.webp' },
      { d: 'wx.qq.com', flag: 'CN', name: 'WeChat API', svc: 'WeChat', logo: '/wechat.webp' },
      {
        d: 'talk.kakao.com',
        flag: '🇰🇷',
        name: 'KakaoTalk',
        svc: 'KakaoTalk',
        logo: '/KakaoTalk.png',
      },
      { d: 'bip.com', flag: '🇹🇷', name: 'BiP', svc: 'BiP', logo: '/BiP.png' },
      { d: 'line.me', flag: 'JP', name: 'LINE', svc: 'LINE', logo: '/LINE.png' },
      { d: 'discord.com', flag: 'US', name: 'Discord', svc: 'Discord', logo: '/discord.svg' },
      {
        d: 'gateway.discord.gg',
        flag: 'US',
        name: 'Discord Gateway',
        svc: 'Discord',
        logo: '/discord.svg',
      },
    ],
  },
  {
    id: 'privacy',
    en: 'Privacy / VPN',
    ru: 'Приватность / VPN',
    sites: [
      { d: 'torproject.org', flag: '', name: 'Tor Project', logo: '/tor.png' },
      { d: 'proton.me', flag: 'CH', name: 'Proton', logo: '/proton.png' },
      { d: 'mullvad.net', flag: 'SE', name: 'Mullvad', logo: '/Mullvad.png' },
      { d: 'nordvpn.com', flag: 'LT', name: 'NordVPN', logo: '/NordVPN.png' },
      { d: 'wireguard.com', flag: '', name: 'WireGuard', logo: '/WireGuard.png' },
    ],
  },
  {
    id: 'hosting',
    en: 'Hosting / Registrars',
    ru: 'Хостинг / Регистраторы',
    sites: [
      { d: 'aws.amazon.com', flag: 'US', name: 'AWS' },
      { d: 'cloud.google.com', flag: 'US', name: 'Google Cloud' },
      { d: 'azure.microsoft.com', flag: 'US', name: 'Azure' },
      { d: 'vultr.com', flag: 'US', name: 'Vultr' },
      { d: 'hetzner.com', flag: 'DE', name: 'Hetzner' },
      { d: 'ovh.com', flag: 'FR', name: 'OVH' },
      { d: 'digitalocean.com', flag: 'US', name: 'DigitalOcean' },
      { d: 'linode.com', flag: 'US', name: 'Linode' },
      { d: 'namecheap.com', flag: 'US', name: 'Namecheap' },
      { d: 'cloudflare.com', flag: 'US', name: 'Cloudflare' },
      { d: 'godaddy.com', flag: 'US', name: 'GoDaddy' },
      { d: 'www.reg.ru', flag: 'RU', name: 'REG.RU' },
      { d: 'selectel.ru', flag: 'RU', name: 'Selectel' },
      { d: 'timeweb.com', flag: 'RU', name: 'Timeweb' },
    ],
  },
  {
    id: 'tech',
    en: 'Tech / Forums',
    ru: 'Технологии / Форумы',
    sites: [
      { d: 'ntc.party', flag: 'DE', name: 'ntc.party', logo: '/ntcparty.png' },
      { d: 'openwrt.org', flag: 'DE', name: 'OpenWrt', logo: '/openwrt.png' },
      { d: 'news.ycombinator.com', flag: 'US', name: 'Hacker News', logo: '/ycombinator.png' },
      { d: 'habr.com', flag: 'RU', name: 'Хабр', logo: '/habr.webp' },
      { d: 'stackoverflow.com', flag: 'US', name: 'Stack Overflow', logo: '/stackoverflow.svg' },
      { d: 'github.com', flag: 'US', name: 'GitHub', logo: '/github.webp' },
      { d: 'gitlab.com', flag: 'US', name: 'GitLab', logo: '/gitlab.svg' },
      { d: 'dev.to', flag: 'US', name: 'DEV', logo: '/devto.png' },
      { d: 'medium.com', flag: 'US', name: 'Medium', logo: '/Medium.png' },
      { d: 'arxiv.org', flag: 'US', name: 'arXiv', logo: '/arXiv.png' },
      { d: 'opennet.ru', flag: 'RU', name: 'OpenNET', logo: '/OpenNET.png' },
      { d: '3dnews.ru', flag: 'RU', name: '3DNews', logo: '/3DNews.png' },
    ],
  },
  {
    id: 'news_by',
    en: 'Media (Belarus)',
    ru: 'СМИ (Беларусь)',
    sites: [
      { d: 'onliner.by', flag: 'BY', name: 'Onliner' },
      { d: 'zerkalo.io', flag: 'BY', name: 'Зеркало' },
      { d: 'spring96.org', flag: 'BY', name: 'Вясна' },
      { d: 'belta.by', flag: 'BY', name: 'БелТА' },
      { d: 'sb.by', flag: 'BY', name: 'СБ Беларусь' },
      { d: 'naviny.by', flag: 'BY', name: 'Naviny' },
      { d: 'belsat.eu', flag: 'BY', name: 'Белсат' },
      { d: 'nashaniva.by', flag: 'BY', name: 'Наша Ніва' },
      { d: 'kp.by', flag: 'BY', name: 'КП Беларусь' },
      { d: 'reform.news', flag: 'BY', name: 'Reform.news' },
    ],
  },
  {
    id: 'software',
    en: 'Software / Dev Tools',
    ru: 'Программное обеспечение / Инструменты',
    sites: [
      { d: 'archive.ubuntu.com', flag: 'GB', name: 'Ubuntu', logo: '/ubuntu.svg' },
      { d: 'dl.fedoraproject.org', flag: 'US', name: 'Fedora', logo: '/fedora.svg' },
      { d: 'deb.debian.org', flag: 'US', name: 'Debian', logo: '/debian.webp' },
      { d: 'archlinux.org', flag: 'US', name: 'Arch Linux', logo: '/archlinux.svg' },
      { d: 'download.opensuse.org', flag: 'DE', name: 'openSUSE', logo: '/openSUSE.png' },
      {
        d: 'catalog.update.microsoft.com',
        flag: 'US',
        name: 'MS Update Catalog',
        logo: '/microsoft.webp',
      },
      { d: 'download.microsoft.com', flag: 'US', name: 'MS Downloads', logo: '/microsoft.webp' },
      { d: 'huggingface.co', flag: 'US', name: 'HuggingFace', logo: '/HuggingFace.png' },
      { d: 'kaggle.com', flag: 'US', name: 'Kaggle', logo: '/Kaggle.png' },
      { d: 'pypi.org', flag: 'US', name: 'PyPI', logo: '/PyPI.png' },
      { d: 'npmjs.com', flag: 'US', name: 'npm', logo: '/npmjs.webp' },
      { d: 'hub.docker.com', flag: 'US', name: 'Docker Hub', logo: '/docker.webp' },
      { d: 'repo.anaconda.com', flag: 'US', name: 'Anaconda', logo: '/Anaconda.png' },
      { d: 'crates.io', flag: 'US', name: 'crates.io', logo: '/crates.png' },
      { d: 'registry.terraform.io', flag: 'US', name: 'Terraform', logo: '/Terraform.png' },
    ],
  },
  {
    id: 'banks',
    en: 'Banks',
    ru: 'Банки',
    sites: [
      { d: 'www.tbank.ru', flag: 'RU', name: 'Т-Банк', logo: '/tinkoffnew.webp' },
      { d: 'sberbank.ru', flag: 'RU', name: 'Сбербанк', logo: '/sberbank.svg' },
      { d: 'alfabank.ru', flag: 'RU', name: 'Альфа-Банк', logo: '/alfabank.svg' },
      { d: 'raiffeisen.ru', flag: 'RU', name: 'Райффайзен', logo: '/raiffeisen.webp' },
      { d: 'chase.com', flag: 'US', name: 'Chase', logo: '/Chase.png' },
      { d: 'bankofamerica.com', flag: 'US', name: 'Bank of America', logo: '/bankofamerica.png' },
      { d: 'wellsfargo.com', flag: 'US', name: 'Wells Fargo', logo: '/Wells-Fargo.png' },
      { d: 'www.hsbc.com', flag: 'GB', name: 'HSBC', logo: '/HSBC.png' },
      { d: 'barclays.co.uk', flag: 'GB', name: 'Barclays', logo: '/Barclays.png' },
      { d: 'lloydsbank.com', flag: 'GB', name: 'Lloyds', logo: '/Lloyds.png' },
      { d: 'natwest.com', flag: 'GB', name: 'NatWest', logo: '/NatWest.png' },
      { d: 'intesasanpaolo.com', flag: 'IT', name: 'Intesa Sanpaolo', logo: '/intesasanpaolo.png' },
      { d: 'unicredit.it', flag: 'IT', name: 'UniCredit', logo: '/unicreditbank.svg' },
      {
        d: 'www.unicreditbank.ru',
        flag: 'RU',
        name: 'UniCredit Russia',
        logo: '/unicreditbank.svg',
      },
      { d: 'santander.com', flag: 'ES', name: 'Santander', logo: '/santander.png' },
      { d: 'bbva.com', flag: 'ES', name: 'BBVA', logo: '/BBVA.png' },
      { d: 'bk.mufg.jp', flag: 'JP', name: 'MUFG', logo: '/MUFG.png' },
      { d: 'www.mizuhobank.co.jp', flag: 'JP', name: 'Mizuho', logo: '/Mizuho.png' },
      { d: 'www.smbc.co.jp', flag: 'JP', name: 'SMBC', logo: '/SMBC.png' },
    ],
  },
];
